language: node_js
node_js: stable

cache:
  directories:
    - 'node_modules'

branches:
  only:
    - master

install:
  - npm install

script:
  - npm run clean
  - npm run build
  - echo "Skipping tests"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: gh-pages
  local-dir: public
  on:
    branch: master
